In [2]:
# using python v3
# using numpy v1.14.3 
import numpy as np

# we can get the version of numpy via below command 
print(np.version.version)


1.14.3


In [3]:
# this is python based list
# python list can have diff type of data like string,  int, float, char etc etc etc 
sample_list = ['a', 1 , 1.2 , '3', 'welcome']


# we shall see the data as its own type
print(sample_list)

['a', 1, 1.2, '3', 'welcome']


In [4]:
sample_np_array  = np.array(sample_list)



# we shall see the data as string type as we have mixed data type
# this is a single dimention array
print(sample_np_array)


['a' '1' '1.2' '3' 'welcome']


In [5]:
# here we shall see the data and the information about the datatype
# as 'welcome' is a string of length 7 we shall the dtype 
# as characters less than length 7 , we will look at dtype later in detail
sample_np_array

array(['a', '1', '1.2', '3', 'welcome'], dtype='<U7')

In [6]:
another_sample_list = ['b', 2 , 2.2 , '4', 'welcome_back']

combine_list = [sample_list, another_sample_list]


# we shall now have a multidimentional array

combine_array = np.array(combine_list)


print(combine_array)


[['a' '1' '1.2' '3' 'welcome']
 ['b' '2' '2.2' '4' 'welcome_back']]


In [7]:
# as 'welcome_back' is a string of length 12 we shall the dtype 
# as characters less than length 12 
combine_array


array([['a', '1', '1.2', '3', 'welcome'],
       ['b', '2', '2.2', '4', 'welcome_back']], dtype='<U12')

In [8]:
# we can get the dimention of array through shape attribue of arrays
combine_array.shape


(2, 5)

In [9]:
# we can get the dtype of array through shape attribue of arrays
combine_array.dtype

dtype('<U12')

In [10]:
#if we create list with only int type data
combine_list_another = [[1,2,3],[3,2,1]]
combine_array_another = np.array(combine_list_another)
combine_array_another.dtype


dtype('int32')

In [11]:
# as mentioned before this shall return us the dimention of the array
combine_array_another.shape


(2, 3)

In [12]:
#if we will see the dtype as int32
combine_array_another.dtype

dtype('int32')

In [13]:
# we can also directly create special arrays like zeros and ones
np.zeros(10 , dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#if you want float one can do 
np.zeros(10, dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# or this , the default type is float 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# I lied it is actually its float64
np.ones(10).dtype

dtype('float64')

In [17]:
# we can also directly create multidimentional arrays too of zeros

np.zeros([2,4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#and ones 
np.ones([3,4], dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
# we can also create an empty array 
# empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. 
# On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.
np.empty(2)


array([3.47571783e-316, 1.42173783e-312])

In [20]:
# as mentioned above we we have no control on the values in the empty array
np.empty(3)


array([0., 0., 0.])

In [21]:
# we can also create identity matrix which is very importrant concept 
# array/matroix shall have diagonal as ones and rest shall be zero
# here we shall create a square matrix of size 5
# as with ones, zeros, etc the default type is float64
np.eye(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
# we can also create an identity matrix with specific dimentions 
sample_eye = np.eye(5,4)
sample_eye 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [23]:
#we can also create the an array with same dimention as another array 
# but filled with values specified by user , the default type is float64 
sample_full_like  = np.full_like(sample_eye, 10, dtype='int32')
sample_full_like

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [24]:
# we can similiarly create array/matrix with ones which has dimention
# same as another array/matrix

sample_ones_like = np.ones_like(sample_full_like)
sample_ones_like

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
# or zeros 

sample_zeros_like = np.zeros_like(sample_full_like)
sample_zeros_like

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
# okay so enough of zeros and ones now lets move beyond that 
# the way we have range function python  which takes start, end and step 
for x in range(3, 20, 2):
    print(x)

3
5
7
9
11
13
15
17
19


In [27]:
# we have similiar function numpy too , its called arange (array range :) and directly returns an array )
numpy_arange = np.arange(3, 20, 2)
print(numpy_arange)

[ 3  5  7  9 11 13 15 17 19]


In [28]:
# just like python too arange would produce values from 'start' to 'end-1'
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# we use the index to get the values from the array
# the index count starts from zero , so this shall produce 
# the first value in the array 
numpy_arange[0]

3

In [30]:
# we can also provide range of values to extract values from the array 
numpy_arange[0:5]


array([ 3,  5,  7,  9, 11])

In [31]:
# we can also index into multidimentionl array 
# as usual the index count starts from zero 
#the below would return us the second row of the identity matrix we created earlier
sample_eye[1]

array([0., 1., 0., 0.])

In [32]:
#this shall produce the second value in the second row 
sample_eye[1][1]

1.0

In [33]:
# now we have the knowledge to create numpy arrays 
# lets have a look on what all airthmatic operations can we do with them 
# this shall return us a ones like array because 1 + 0 =  1 :)
sample_ones_like + sample_zeros_like

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
# we shall create an array/matrix with values as 2
sample_twos = np.full_like(sample_ones_like, 2, dtype='int32')
# and then we shall add the two arrays/matrix
sample_threes = sample_ones_like + sample_twos

# 1 + 2 =  3
sample_threes

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [35]:
# we can also do substracation
sample_ones = sample_threes - sample_twos

# 3 - 2 = 1 
sample_ones 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
# we can compare two matrix for equallity 

np.array_equal(sample_ones, sample_ones_like)

True

In [37]:
# we can also do multiplication of two matrix 
sample_sixs = sample_threes * sample_twos

# 3 * 2 = 6 
sample_sixs

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [38]:
# we can also do power operation on the two matrixs
# as shown in above scenarios each value is powered up by the 
# value at the same coordinate/position of second matrix 
sample_nines = sample_threes ** sample_twos
sample_nines

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int32)

In [39]:
# we can also do division of two matrix 
# values in same positions are used to do the operation on individual values
sample_sixs / sample_twos


array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [40]:
# we can also do scalar operation with array/matrix which really makes life better

# this shall return a matrix with each value have +1 
sample_ones_like + 1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [41]:
# similarly we can do substraction  
# we shall get the zero matrix 
sample_ones_like - 1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
# similarly we can do scalar multiplication 
# we shall get the twos matrix 
sample_ones_like * 2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [43]:
#we can also do the scalar division 
sample_threes / 2

array([[1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5]])

In [44]:
# or the exponential operation
# 3**2 = 9
sample_threes  ** 2

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int32)

In [45]:
# we can also do easy assignment on a portion of array and slicing 

# lets create an array
numpy_array = np.arange(2, 20, 2)
numpy_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
# here we are telling the numpy to change the values in array from index 0 to 4 to 10 
# note that the 5th value has index 4 
numpy_array[0:5] =  10
numpy_array

array([10, 10, 10, 10, 10, 12, 14, 16, 18])

In [47]:
# we can extract portion of an array by slicing 
portion_array = numpy_array[5:]
portion_array

array([12, 14, 16, 18])

In [48]:
#  we can change the entire array to an specific value 
numpy_array[:] = 100
numpy_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [49]:
# what you think would be the values of portion_array ? we never changed it right ?
# here is the magic 
portion_array

array([100, 100, 100, 100])

In [50]:
# in numpy we use the same data i.e. we have only one copy of the array 
# and thus if we change array the slice/portion of it would 
# also see the change , -1 will point till the second last value in the array just like the 
# normal python slices
portion_array[:-1] = 10
# now the main array i.e numpy_array would also change 

numpy_array 

array([100, 100, 100, 100, 100,  10,  10,  10, 100])

In [89]:
# we can get the unique values through unique function
np.unique(numpy_array )

array([ 10, 100])

In [51]:
# so if you have to copy an array then one has to explisitly specify that to numpy 
# for this we have use the copy method

copied_array = np.copy(numpy_array)
copied_array

array([100, 100, 100, 100, 100,  10,  10,  10, 100])

In [52]:
# and now any change in this copy of array exist in diff memory space
copied_array[:] = 0
copied_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# and it wont impact the original array
numpy_array

array([100, 100, 100, 100, 100,  10,  10,  10, 100])

In [54]:
# we can also do the slicing of the multidimentional arrays 
twoD_array = np.array([[1,2,3,13],[4,5,6,14],[7,8,9,15],[10,11,12,16]])
# first value first dimention in our case row
# second value second dimention i.e. coloumn
# 
twoD_array[0:3,1:]

array([[ 2,  3, 13],
       [ 5,  6, 14],
       [ 8,  9, 15]])

In [55]:
# but there is another way to do the indexing
# and its is particularly useful when we need to 
# selects non-sequential rows/coloums
# here we select the first row and third row 
twoD_array[[0,2]]

array([[ 1,  2,  3, 13],
       [ 7,  8,  9, 15]])

In [56]:
# there is no compultion of order etc 
twoD_array[[3,0,2]]

array([[10, 11, 12, 16],
       [ 1,  2,  3, 13],
       [ 7,  8,  9, 15]])

In [57]:
# we can also select the relevant coloums too
twoD_array[[3,0,2],[0,2,1]]

array([10,  3,  8])

In [62]:
twoD_array

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

In [77]:
#returns true if any value is true or non-zero
twoD_array.any()

True

In [79]:
#returns true if all the values are true or non-zero
twoD_array.all()

True

In [63]:
twoD_array.sum()

136

In [64]:
# we can take sum based on axis
# sum of all the values in each coloumn
twoD_array.sum(0)

array([22, 26, 30, 58])

In [67]:
# we can take sum based on axis
# sum of all the values in each row
twoD_array.sum(1)

array([19, 29, 39, 49])

In [68]:
#we can also calculate mean
twoD_array.mean()

8.5

In [69]:
twoD_array.mean(0)

array([ 5.5,  6.5,  7.5, 14.5])

In [70]:
twoD_array.mean(1)

array([ 4.75,  7.25,  9.75, 12.25])

In [71]:
#we can also calculate std
twoD_array.std()

4.6097722286464435

In [81]:
twoD_array.std(0)

array([3.35410197, 3.35410197, 3.35410197, 1.11803399])

In [85]:
twoD_array.std(1)

array([4.81534007, 3.96074488, 3.1124749 , 2.27760839])

In [86]:
# we can sort the array 
s = twoD_array.std(1)
s.sort()
s

array([2.27760839, 3.1124749 , 3.96074488, 4.81534007])

In [87]:
# we can sort in reverse order too
# trick is to pass negative of array, and then again negate it
-np.sort(-twoD_array)

array([[13,  3,  2,  1],
       [14,  6,  5,  4],
       [15,  9,  8,  7],
       [16, 12, 11, 10]])

In [74]:
#we can also calculate variance
twoD_array.var()

21.25

In [75]:
twoD_array.var(1)

array([23.1875, 15.6875,  9.6875,  5.1875])

In [76]:
twoD_array.var(0)

array([11.25, 11.25, 11.25,  1.25])