In [3]:
import numpy as np


In [4]:
one = np.ones([3,4], dtype='int32')

two = np.ones([3,4], dtype='int32')*2

eye = np.eye(3,4,dtype='int32')

eye_copy = np.copy(eye)


eye = 8 - eye_copy 

start_array = one*5 + two**2 - eye_copy 
start_array

array([[8, 9, 9, 9],
       [9, 8, 9, 9],
       [9, 9, 8, 9]])

In [5]:
eye

array([[7, 8, 8, 8],
       [8, 7, 8, 8],
       [8, 8, 7, 8]])

In [6]:
second_array = start_array.T
second_array

array([[8, 9, 9],
       [9, 8, 9],
       [9, 9, 8],
       [9, 9, 9]])

we can also use the reshare and nrange to create a matrix from a range 


In [9]:
rarr = np.arange(40).reshape((8,5))
rarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

As we mentioned before that the original array/matrix is not modified but we are provided with the new copy of the array

In [10]:
rarr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35],
       [ 1,  6, 11, 16, 21, 26, 31, 36],
       [ 2,  7, 12, 17, 22, 27, 32, 37],
       [ 3,  8, 13, 18, 23, 28, 33, 38],
       [ 4,  9, 14, 19, 24, 29, 34, 39]])

we can also swap axis of a matrix


In [35]:
rarr.swapaxes(1,1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

numpy supports the dot product of arrays 


In [12]:
np.dot(rarr,rarr.T)

array([[  30,   80,  130,  180,  230,  280,  330,  380],
       [  80,  255,  430,  605,  780,  955, 1130, 1305],
       [ 130,  430,  730, 1030, 1330, 1630, 1930, 2230],
       [ 180,  605, 1030, 1455, 1880, 2305, 2730, 3155],
       [ 230,  780, 1330, 1880, 2430, 2980, 3530, 4080],
       [ 280,  955, 1630, 2305, 2980, 3655, 4330, 5005],
       [ 330, 1130, 1930, 2730, 3530, 4330, 5130, 5930],
       [ 380, 1305, 2230, 3155, 4080, 5005, 5930, 6855]])

we can also create 3d matrix with numpy


In [17]:
rarr3d = np.arange(40).reshape((2,5,4))
rarr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [18]:
rarr3d.T

array([[[ 0, 20],
        [ 4, 24],
        [ 8, 28],
        [12, 32],
        [16, 36]],

       [[ 1, 21],
        [ 5, 25],
        [ 9, 29],
        [13, 33],
        [17, 37]],

       [[ 2, 22],
        [ 6, 26],
        [10, 30],
        [14, 34],
        [18, 38]],

       [[ 3, 23],
        [ 7, 27],
        [11, 31],
        [15, 35],
        [19, 39]]])

In [ ]:
numpy supports many universal functions that canb be applied to the matrix/arrays
these functions are applied to each value of the matrix

In [36]:
np.sqrt(rarr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ]])

In [38]:
np.add(rarr,1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [39]:
np.divide(rarr, 2)

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. ],
       [17.5, 18. , 18.5, 19. , 19.5]])

In [43]:
np.sqrt(rarr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ]])

In [41]:
np.square(rarr)

array([[   0,    1,    4,    9,   16],
       [  25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196],
       [ 225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156],
       [1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [44]:
np.exp(rarr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10],
       [7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
        3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14],
       [1.58601345e+15, 4.31123155e+15, 1.17191424e+16, 3.18559318e+16,
        8.65934004e+16]])

In [46]:
np.log(np.exp(rarr))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.]])

In [47]:
np.log2(np.exp(rarr))

array([[ 0.        ,  1.44269504,  2.88539008,  4.32808512,  5.77078016],
       [ 7.2134752 ,  8.65617025, 10.09886529, 11.54156033, 12.98425537],
       [14.42695041, 15.86964545, 17.31234049, 18.75503553, 20.19773057],
       [21.64042561, 23.08312065, 24.5258157 , 25.96851074, 27.41120578],
       [28.85390082, 30.29659586, 31.7392909 , 33.18198594, 34.62468098],
       [36.06737602, 37.51007106, 38.9527661 , 40.39546114, 41.83815619],
       [43.28085123, 44.72354627, 46.16624131, 47.60893635, 49.05163139],
       [50.49432643, 51.93702147, 53.37971651, 54.82241155, 56.26510659]])

In [49]:
np.add(np.sqrt(rarr), rarr)

array([[ 0.        ,  2.        ,  3.41421356,  4.73205081,  6.        ],
       [ 7.23606798,  8.44948974,  9.64575131, 10.82842712, 12.        ],
       [13.16227766, 14.31662479, 15.46410162, 16.60555128, 17.74165739],
       [18.87298335, 20.        , 21.12310563, 22.24264069, 23.35889894],
       [24.47213595, 25.58257569, 26.69041576, 27.79583152, 28.89897949],
       [30.        , 31.09901951, 32.19615242, 33.29150262, 34.38516481],
       [35.47722558, 36.56776436, 37.65685425, 38.74456265, 39.83095189],
       [40.91607978, 42.        , 43.08276253, 44.164414  , 45.244998  ]])

In [50]:
np.maximum(np.sqrt(rarr), rarr)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.]])

In [52]:
np.minimum(np.sqrt(rarr), rarr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ]])

In [54]:
np.subtract(rarr, np.sqrt(rarr) )

array([[ 0.        ,  0.        ,  0.58578644,  1.26794919,  2.        ],
       [ 2.76393202,  3.55051026,  4.35424869,  5.17157288,  6.        ],
       [ 6.83772234,  7.68337521,  8.53589838,  9.39444872, 10.25834261],
       [11.12701665, 12.        , 12.87689437, 13.75735931, 14.64110106],
       [15.52786405, 16.41742431, 17.30958424, 18.20416848, 19.10102051],
       [20.        , 20.90098049, 21.80384758, 22.70849738, 23.61483519],
       [24.52277442, 25.43223564, 26.34314575, 27.25543735, 28.16904811],
       [29.08392022, 30.        , 30.91723747, 31.835586  , 32.755002  ]])

numpy also supports feature to save and load arrays 


np.save('saved', rarr)

In [ ]:
the rarr will be saved as a saved.npy file

In [60]:
np.load('saved.npy')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [65]:
rarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

we can also save multiple arrays in one shot 

In [66]:
np.savez('combined', x=rarr, y=rarr.T)

savez uses .npz format to save the files

In [67]:
zip = np.load('combined.npz')

In [69]:
zip['x']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [70]:
zip['y']

array([[ 0,  5, 10, 15, 20, 25, 30, 35],
       [ 1,  6, 11, 16, 21, 26, 31, 36],
       [ 2,  7, 12, 17, 22, 27, 32, 37],
       [ 3,  8, 13, 18, 23, 28, 33, 38],
       [ 4,  9, 14, 19, 24, 29, 34, 39]])

npz and npy are binary files, we can also save the array as a text filie 

In [72]:
np.savetxt('x.txt', rarr)

In [73]:
np.loadtxt('x.txt')

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.]])

we can also specify our custom delimiter, but we have to specify the same when we load the array from text file

In [81]:
np.savetxt('y.txt', rarr.T, delimiter=' , ')

In [82]:
np.loadtxt('y.txt', delimiter=' , ')

array([[ 0.,  5., 10., 15., 20., 25., 30., 35.],
       [ 1.,  6., 11., 16., 21., 26., 31., 36.],
       [ 2.,  7., 12., 17., 22., 27., 32., 37.],
       [ 3.,  8., 13., 18., 23., 28., 33., 38.],
       [ 4.,  9., 14., 19., 24., 29., 34., 39.]])